apiVersion: v1
kind: Namespace
metadata:
   name: omnifood
   labels:
     name: omnifood
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: webserver
   namespace: omnifood 
   labels:
     app: webserver
spec: 
  replicas: 1
  selector:
    matchLabels:
       app: webserver
  template:
    metadata:
       name: omnifood
       labels:
           app: webserver
    spec:
       containers:
          - name: omnifood
            image: spersis/omnifood
            securityContext:
              privileged: true
            ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
   name: omnifood-service
   namespace: omnifood
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80